name: style

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: "yarn"

            - name: Build monorepo
              run: yarn

            - name: Run Prettier
              run: yarn prettier

            - name: Run Eslint
              run: yarn lint
